<?xml version="1.0"?>
<package format="2">
  <name>catatron_description</name>
  <version>1.0.0</version>
  <description>The catatron_description package</description>

  <maintainer email="lcatatronl@gmail.com">lcatatronl</maintainer>

  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

</package>
